import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { AlertCircle, Loader2, Mic, Clock, Sun } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Link } from "react-router-dom";

const Demo = () => {
  const navigate = useNavigate();
  const [firstName, setFirstName] = useState("");
  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    if (!firstName.trim() || !email.trim()) {
      setError("Please enter your name and email");
      return;
    }

    // Basic email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      setError("Please enter a valid email address");
      return;
    }

    setLoading(true);

    try {
      // Check if email already exists
      const { data: existing } = await supabase
        .from('demo_leads')
        .select('id, first_name, discount_code')
        .eq('email', email.toLowerCase())
        .single();

      if (existing) {
        // Already have this lead, just continue to demo
        sessionStorage.setItem('demo_user', JSON.stringify({
          firstName: existing.first_name,
          email: email.toLowerCase(),
          discountCode: existing.discount_code
        }));
      } else {
        // Create new lead - discount code auto-generated by trigger
        const { data: newLead, error: insertError } = await supabase
          .from('demo_leads')
          .insert({
            first_name: firstName.trim(),
            email: email.toLowerCase().trim(),
            demo_started_at: new Date().toISOString()
          })
          .select('discount_code')
          .single();

        if (insertError) {
          console.error('Demo lead insert error:', insertError);
          setError("Something went wrong. Please try again.");
          setLoading(false);
          return;
        }

        sessionStorage.setItem('demo_user', JSON.stringify({
          firstName: firstName.trim(),
          email: email.toLowerCase().trim(),
          discountCode: newLead?.discount_code
        }));
      }

      // Navigate to live demo
      navigate('/demo/live');
    } catch (err: any) {
      console.error('Demo signup error:', err);
      setError("Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Simple Header */}
      <header className="p-4">
        <Link to="/" className="flex items-center gap-2 w-fit">
          <img src="/stocker-ai-logo.jpg" alt="Stocker AI" className="h-14 w-auto" />
          <span className="text-xl font-bold text-foreground">Stocker AI</span>
        </Link>
      </header>

      {/* Main Content */}
      <main className="flex-1 flex flex-col items-center justify-center px-4 py-8">
        <div className="w-full max-w-lg">
          {/* Pain Scene - The Emotional Hook */}
          <div className="text-center mb-8">
            <div className="flex justify-center gap-4 mb-6">
              <div className="p-3 bg-primary/10 rounded-full">
                <Sun className="h-6 w-6 text-primary" />
              </div>
              <div className="p-3 bg-primary/10 rounded-full">
                <Clock className="h-6 w-6 text-primary" />
              </div>
            </div>

            <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
              6:00 AM. The Warehouse.
            </h1>

            <div className="text-lg text-muted-foreground space-y-4 text-left max-w-md mx-auto">
              <p>
                You're staring at a route sheet, squinting at tiny print.
                <span className="text-foreground font-medium"> Which slot was that?</span>
              </p>
              <p>
                Hands full of product. Phone balanced on a bin.
                <span className="text-foreground font-medium"> Counting. Re-counting.</span>
              </p>
              <p>
                New driver started this week. Still making mistakes.
                <span className="text-foreground font-medium"> You're fixing them.</span>
              </p>
              <p className="text-foreground font-semibold pt-2">
                What if your earbuds told you exactly what to pick next?
              </p>
            </div>
          </div>

          {/* Form Card */}
          <div className="card-base border border-border">
            <div className="text-center mb-6">
              <div className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-500/10 border border-emerald-500/20 rounded-full mb-4">
                <Mic className="h-4 w-4 text-emerald-400" />
                <span className="text-sm font-medium text-emerald-400">Live Voice Demo</span>
              </div>
              <h2 className="text-xl font-bold text-foreground mb-1">
                Try it yourself. Right now.
              </h2>
              <p className="text-muted-foreground text-sm">
                30 seconds. Real voice commands. Zero signup required.
              </p>
            </div>

            {error && (
              <div className="mb-4 p-3 bg-destructive/10 border border-destructive/20 rounded-lg flex items-start gap-2">
                <AlertCircle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />
                <p className="text-sm text-destructive">{error}</p>
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="firstName">First name</Label>
                <Input
                  id="firstName"
                  type="text"
                  placeholder="What should Stocker call you?"
                  value={firstName}
                  onChange={(e) => setFirstName(e.target.value)}
                  required
                  className="text-lg py-6"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="Where should we send your discount?"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                  className="text-lg py-6"
                />
              </div>

              <Button
                type="submit"
                className="w-full h-16 text-xl font-bold bg-emerald-600 hover:bg-emerald-700 rounded-xl shadow-lg shadow-emerald-500/30"
                disabled={loading}
              >
                {loading ? (
                  <>
                    <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                    Setting up...
                  </>
                ) : (
                  <>
                    <Mic className="mr-2 h-5 w-5" />
                    START THE DEMO!
                  </>
                )}
              </Button>

              <p className="text-xs text-center text-muted-foreground">
                Works best with earbuds or headphones. Find a quiet spot.
              </p>
            </form>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Demo;
